image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - sonarqube-check

before_script:
  - cp .env.example .env

# build:
#   stage: build
#   script:
#     - docker-compose build

testing:
  stage: test
  script:
    - docker-compose build
    - docker-compose run --name tests_app app /bin/bash generate_unit_tests_report.sh  # run tests for coverage
    - docker cp tests_app:/app/reports/ .  # copy coverage reports into CI
#     - docker-compose run app black --check .
#     - docker-compose run app isort . --check-only --profile black
#     - docker-compose run app pytest -v --junitxml=reports/pytest.xml
  artifacts:
    paths:
      - reports/coverage.xml  # There is a change that these expire 1 hour from last CI build
      - reports/pytest.xml

sonarqube-check:
  needs: ["testing"]
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - ls reports/
    - sonar-scanner
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

