version: '3.7'

services:
  app:
    container_name: document-processor-prod
    image: andrewrutherfoord/ing_identity_document_classifier:latest
    build:
      context: ./document_processor
      dockerfile: Dockerfile.prod
    command: uvicorn main:app --app-dir ./src/ --host 0.0.0.0 --port 8000
    ports:
      - ${port:-8000}:8000
    env_file: .env
    environment:
      MODE: PRODUCTION
    volumes:
      - ./models/:/app/src/document_processor/pipeline/models/
