version: '3.7'

services:
  app:
    container_name: api
    build: ./api
    command: uvicorn main:app --app-dir ./api/src/ --host 0.0.0.0 --port ${port:-8000} --reload
    volumes:
      - ./api/:/app/api
      - ./models/:/app/models
    ports:
      - ${port:-8000}:${port:-8000}
    env_file: .env
    environment:
      MODE: DEVELOPMENT