version: '3.7'

services:
  app:
    container_name: document-processor-prod
    build:
      context: ./document_processor
      dockerfile: Dockerfile.prod
    command: uvicorn main:app --app-dir ./src/ --host 0.0.0.0 --port 8000
    ports:
      - ${port:-8000}:8000
    env_file: .env
